# Generated by Django 5.2.3 on 2025-06-29 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FractionalCurrencyVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='fractioanl_currencies/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('III', 'Three Cents'), ('V', 'Five Cents'), ('X', 'Ten Cents'), ('XXV', 'Twenty Five Cents'), ('L', 'Fifty Cents')], max_length=5)),
                ('issue', models.CharField(choices=[('I', 'First Issue'), ('II', 'Second Issue'), ('III', 'Third Issue'), ('IV', 'Fourth Issue'), ('V', 'Fifth Issue')], max_length=5)),
            ],
        ),
    ]
