# Generated by Django 5.2.3 on 2025-06-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fractionalcurrencyvariety',
            name='fr_number',
            field=models.IntegerField(default=0, help_text='Fr Number.'),
        ),
        migrations.AddField(
            model_name='fractionalcurrencyvariety',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fractionalcurrencyvariety',
            name='year',
            field=models.CharField(default='2025', max_length=100),
        ),
    ]
