# Generated by Django 5.2.3 on 2025-08-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('large_size_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largesizecurrencyvariety',
            name='type',
            field=models.CharField(choices=[('Gold Certificates', 'Gold Certificates'), ('Silver Certificates', 'Silver Certificates'), ('Legal Tender', 'Legal Tender'), ('Federal Reserve Bank Note', 'Federal Reserve Bank Note'), ('Federal Reserve Note5', 'Federal Reserve Note'), ('Treasury or Coin Note', 'Treasury or Coin Note'), ('National Bank Note', 'National Bank Note')], max_length=25),
        ),
    ]
