# Generated by Django 5.2.3 on 2025-08-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('large_size_notes', '0002_alter_largesizecurrencyvariety_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='largesizecurrencyvariety',
            name='serial_number',
            field=models.CharField(default='', max_length=32),
        ),
    ]
