# Generated by Django 5.2.3 on 2025-07-23 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fractionalCurrencyVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(default='2025', max_length=100)),
                ('fr_number', models.IntegerField(default=0, help_text='Fr Number.')),
                ('price_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(upload_to='fractional_currencies/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('III', 'Three Cents'), ('V', 'Five Cents'), ('X', 'Ten Cents'), ('XV', 'Fifteen Cents'), ('XXV', 'Twenty Five Cents'), ('L', 'Fifty Cents')], max_length=5)),
                ('issue', models.CharField(choices=[('I', 'First Issue'), ('II', 'Second Issue'), ('III', 'Third Issue'), ('IV', 'Fourth Issue'), ('V', 'Fifth Issue')], max_length=5)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
