# Generated by Django 5.2.3 on 2025-07-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fractional_currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fractionalcurrencyvariety',
            name='portrait',
            field=models.CharField(default='', max_length=100),
        ),
    ]
