# Generated by Django 5.2.3 on 2025-08-24 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='smallSizeCurrencyVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(default='2025', max_length=100)),
                ('fr_number', models.IntegerField(default=0, help_text='Fr Number.')),
                ('serial_number', models.CharField(default='', max_length=32)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(upload_to='small_size_notes_inventory/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('denomination', models.CharField(choices=[('$1', 'One Dollars'), ('$2', 'Two Dollars'), ('$5', 'Five Dollars'), ('$10', 'Ten Dollars'), ('$20', 'Twenty Dollars'), ('$50', 'Fifty Dollars'), ('$50', 'Hundred Dollars')], max_length=5)),
                ('type', models.CharField(choices=[('Gold Certificates', 'Gold Certificates'), ('Silver Certificates', 'Silver Certificates'), ('Legal Tender', 'Legal Tender'), ('Federal Reserve Bank Note', 'Federal Reserve Bank Note'), ('Federal Reserve Note5', 'Federal Reserve Note'), ('Treasury or Coin Note', 'Treasury or Coin Note'), ('National Bank Note', 'National Bank Note')], max_length=25)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
